apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-based-classification-deployment
  namespace: banking-classification
  labels:
    application: banking-based-classification
spec:
  replicas: 2
  selector:
    matchLabels:
      application: banking-based-classification
  template:
    metadata:
      labels:
        application: banking-based-classification
    spec:
      containers:
      - name: banking-based-classification
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/new_banking_repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: ENV
            value: "dev"                   
          - name: BUCKET_NAME
            value: "topic-bucket-banking"     
        resources:
          requests:
            memory: "500Mi"
            cpu: '0.25'
          limits:
            memory: "1024Mi"
            cpu: '1'
        # livenessProbe:
        #   httpGet:
        #     path: /health-status
        #     port: 5000
        #     scheme: HTTP
      restartPolicy: Always
