kind: Service
apiVersion: v1
metadata:
  name: banking-based-classification-svc
  namespace: banking-classification
  labels:
    application: banking-based-classification
    stage: development
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-security-groups: 
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    application: banking-based-classification
